import streamlit as st
import pandas as pd
# استيراد باقي المكتبات (torch, xgboost, transformers)

# إعداد واجهة المستخدم
st.set_page_config(page_title="UK GDPR Legal AI", layout="wide")

st.title("⚖️ UK GDPR Risk & Fine Predictor")
st.markdown("تحليل ذكي للمخالفات القانونية بناءً على سوابق الـ ICO البريطاني")

# --- القائمة الجانبية ---
with st.sidebar:
    st.header("إعدادات النظام")
    st.info("النظام يستخدم Legal-BERT + XGBoost لتحليل البيانات.")
    uploaded_file = st.file_input("ارفع ملف الشركة (PDF/DOCX)", type=["pdf", "docx"])

# --- المنطقة الرئيسية ---
if uploaded_file is not None:
    with st.spinner('جاري تحليل المستند قانونياً...'):
        # هنا تضعين دوال الاستخراج والتحليل التي كتبناها سابقاً
        # text = extract_text(uploaded_file)
        # prediction = model_predictor.predict(...)
        
        # عرض النتائج في بطاقات (Cards)
        col1, col2 = st.columns(2)
        with col1:
            st.metric(label="الغرامة المتوقعة", value=f"£{500000:,.2f}")
        with col2:
            st.error("مستوى المخاطرة: مرتفع")
            
        st.subheader("التعليل القانوني (Legal Reasoning)")
        st.write("بناءً على المادة 32 من UK GDPR...")
else:
    st.warning("رجاءً ارفعي ملفاً للبدء في التحليل.")

# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajA_5Pz5vFyjnQelKGvxsjS8V-XqNjhb
"""

!pip install pymupdf python-docx transformers torch scikit-learn

import os
import fitz  # PyMuPDF
import docx

# قائمة بأسماء الملفات التي رفعتها
uploaded_files = [
    "23andme-penalty-notice.pdf",
    "capita-plc-and-cpsl-monetary-penalty-notice.pdf",
    "lastpass-uk-ltd-penalty-notice.pdf",
    "سياسـة-الخصوصيـة.pdf",
    "gdpr.pdf",
    "breach.docx",
    "Fines.docx",
    "small businesses make up.docx"
]

def load_data(file_list):
    documents_content = []
    for file_name in file_list:
        if not os.path.exists(file_name):
            print(f"⚠️ الملف {file_name} غير موجود، تأكدي من رفعه.")
            continue

        text = ""
        if file_name.endswith(".pdf"):
            with fitz.open(file_name) as doc:
                text = "".join([page.get_text() for page in doc])
        elif file_name.endswith(".docx"):
            doc = docx.Document(file_name)
            text = "\n".join([p.text for p in doc.paragraphs])

        documents_content.append({"filename": file_name, "text": text})
    return documents_content

# تنفيذ القراءة
data = load_data(uploaded_files)
print(f"✅ تم تحميل {len(data)} ملفات بنجاح.")

from transformers import AutoTokenizer, AutoModel
import torch

# تحميل الموديل المتخصص في القانون
tokenizer = AutoTokenizer.from_pretrained("nlpaueb/legal-bert-base-uncased")
model = AutoModel.from_pretrained("nlpaueb/legal-bert-base-uncased")

def get_legal_embedding(text):
    # نأخذ جزءاً من النص (أول 512 توكن) لتمثيل الملف
    inputs = tokenizer(text[:2000], return_tensors="pt", truncation=True, padding=True, max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    # نأخذ المتوسط لتمثيل النص بالكامل في "متجه" واحد
    return outputs.last_hidden_state.mean(dim=1).squeeze().numpy()

# تحويل كل ملف إلى رقم (Vector)
file_vectors = [get_legal_embedding(d['text']) for d in data]

from sklearn.cluster import KMeans

# سنطلب منه تقسيمهم لـ 3 مجموعات كمثال (عقوبات تقنية، سياسات عامة، إحصائيات)
num_clusters = 3
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
clusters = kmeans.fit_predict(file_vectors)

# عرض النتائج
for i, cluster_id in enumerate(clusters):
    print(f"📁 الملف: {data[i]['filename']} ---> تم وضعه في المجموعة: {cluster_id}")

import pandas as pd

# نقوم بإنشاء جدول يربط كل ملف بتصنيفه وقيمته (بيانات تدريبية للموديل)
dataset_list = []

for doc in data:
    # هنا تضعين القيم بناءً على قراءتك للملفات (كمثال)
    if "23andme" in doc['filename']:
        fine_value = 0 # (إذا لم تكن الغرامة نهائية بعد) أو ضعي القيمة المذكورة
        category = "Security Breach"
        cooperation = 1 # 1 يعني تعاونوا، 0 لا
    elif "lastpass" in doc['filename']:
        fine_value = 6000000 # مثال
        category = "Credential Stuffing"
        cooperation = 1
    # ... وهكذا للبقية

    dataset_list.append({
        "filename": doc['filename'],
        "category": category,
        "cooperation_score": cooperation,
        "target_fine": fine_value
    })

df = pd.DataFrame(dataset_list)
print(df.head())

import pandas as pd
import re

def extract_fine_amount(text):
    # البحث عن علامة الجنيه الإسترليني متبوعة بأرقام
    match = re.search(r'£(\d{1,3}(?:,\d{3})*)', text)
    if match:
        return int(match.group(1).replace(',', ''))
    return 0

rows = []
# تأكدي أننا نستخدم "data" وهي القائمة التي تحتوي على الملفات التي حملناها سابقاً
for doc in data:
    fine = extract_fine_amount(doc['text'])

    # ميزات تقنية (Feature Engineering)
    has_mfa = 1 if "MFA" in doc['text'].upper() else 0
    is_children = 1 if "children" in doc['text'].lower() else 0

    rows.append({
        "file": doc['filename'],
        "fine_amount": fine,
        "mfa_failure": has_mfa,
        "children_privacy": is_children,
        "cluster_id": clusters[data.index(doc)] # التصحيح هنا
    })

df_final = pd.DataFrame(rows)
print("✅ تم إنشاء جدول الميزات بنجاح:")
print(df_final)

import pandas as pd
import re

def extract_fine_amount(text):
    # بحث عن العملة البريطانية متبوعة بأرقام (مثال: £3,076,320)
    match = re.search(r'£(\d{1,3}(?:,\d{3})*)', text)
    if match:
        return int(match.group(1).replace(',', ''))
    return 0

# بناء الجدول
rows = []
for doc in data:
    fine = extract_fine_amount(doc['text'])
    # سنبحث عن كلمات مفتاحية برمجياً لتحديد نوع المخالفة
    has_mfa = 1 if "MFA" in doc['text'].upper() else 0
    is_children = 1 if "children" in doc['text'].lower() else 0

    rows.append({
        "file": doc['filename'],
        "fine_amount": fine,
        "mfa_failure": has_mfa,
        "children_privacy": is_children,
        "cluster_id": clusters[data.index(doc)] # الربط مع الخطوة السابقة
    })

df_final = pd.DataFrame(rows)
print(df_final)

import pandas as pd
import re

def extract_fine_amount(text):
    # بحث عن العملة البريطانية متبوعة بأرقام (مثال: £3,076,320)
    match = re.search(r'£(\d{1,3}(?:,\d{3})*)', text)
    if match:
        return int(match.group(1).replace(',', ''))
    return 0

# بناء الجدول النهائي للتدريب
rows = []
for doc in data:
    fine = extract_fine_amount(doc['text'])

    # ميزات بحث ذكية (مبسطة هنا)
    has_mfa_issue = 1 if any(word in doc['text'].upper() for word in ["MFA", "MULTI-FACTOR"]) else 0
    is_children_issue = 1 if "children" in doc['text'].lower() else 0

    rows.append({
        "file": doc['filename'],
        "fine_amount": fine,
        "mfa_failure": has_mfa_issue,
        "children_privacy": is_children_issue,
        "cluster_id": clusters[data.index(doc)]
    })

df_final = pd.DataFrame(rows)
# سنقوم بحذف الملفات التي ليس لها غرامة (مثل نصوص القوانين) لتدريب موديل التوقع
train_df = df_final[df_final['fine_amount'] > 0]
print("✅ جدول البيانات جاهز للتدريب:")
print(train_df)

import xgboost as xgb
from sklearn.model_selection import train_test_split

# تحديد المدخلات (Features) والمخرج (Target)
X = train_df[['mfa_failure', 'children_privacy', 'cluster_id']]
y = train_df['fine_amount']

# تدريب الموديل
model_xgb = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=100)
model_xgb.fit(X, y)

print("🚀 الموديل تدرب بنجاح على السوابق البريطانية!")

import xgboost as xgb
from sklearn.model_selection import train_test_split
import numpy as np

# 1. تجهيز البيانات للتدريب
# سنستبعد الملفات التي ليس لها غرامة (التي غرامتها 0) لتدريب الموديل على حالات العقوبات فقط
train_df = df_final[df_final['fine_amount'] > 0].copy()

# المدخلات (Features) والمخرج (Target)
X = train_df[['mfa_failure', 'children_privacy', 'cluster_id']]
y = train_df['fine_amount']

# 2. بناء الموديل
# نستخدم Regressor لأننا نتوقع "رقم" (مبلغ الغرامة) وليس تصنيفاً فقط
model_xgb = xgb.XGBRegressor(
    objective='reg:squarederror',
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3
)

# 3. تدريب الموديل
model_xgb.fit(X, y)

print("🚀 تم تدريب الموديل بنجاح على السوابق البريطانية!")

def predict_company_risk(has_mfa, has_children_data, cluster_id):
    # تحويل المدخلات لشكل يفهمه الموديل
    input_data = np.array([[has_mfa, has_children_data, cluster_id]])
    prediction = model_xgb.predict(input_data)[0]

    # ضمان أن الغرامة لا تظهر بالسالب
    final_fine = max(0, prediction)

    print(f"--- 🛡️ تحليل المخاطر البريطانية (UK GDPR) ---")
    print(f"🔹 التوقع الأولي للغرامة: £{final_fine:,.2f}")

    if has_mfa == 1:
        print("⚠️ تنبيه: تم اكتشاف ضعف في الـ MFA، مما يرفع احتمالية الغرامة بناءً على سوابق LastPass و 23andMe.")

    return final_fine

# تجربة المحاكي على شركة افتراضية لديها مشكلة في MFA
print("\nمثال لمحاكاة شركة جديدة:")
predicted_value = predict_company_risk(has_mfa=1, has_children_data=0, cluster_id=0)

# تثبيت المكتبة أولاً
!pip install streamlit -q

import streamlit as st

# عنوان التطبيق
st.title("🛡️ نظام تقييم الامتثال لـ UK GDPR")
st.markdown("---")

# 1. منطقة الإدخال
st.subheader("وصف الحالة أو المشكلة التقنية")
user_input = st.text_area("اكتبي تفاصيل الحدث أو سياسة الشركة هنا:",
                          placeholder="مثال: اكتشفنا اختراقاً لقاعدة البيانات ولم نكن نفعل خاصية MFA...")

# خيارات إضافية للتحليل
col1, col2 = st.columns(2)
with col1:
    company_size = st.selectbox("حجم الشركة", ["Micro", "Small", "Medium", "Large"])
with col2:
    sector = st.selectbox("القطاع", ["Tech", "Finance", "Healthcare", "Retail"])

# 2. منطق المعالجة (عند الضغط على الزر)
if st.button("تحليل الامتثال وتوقع المخاطر"):
    if user_input:
        with st.spinner('جاري تحليل النص باستخدام Legal-BERT ومقارنته بسوابق الـ ICO...'):

            # هنا نقوم بالربط مع الموديلات التي تدربت سابقاً
            # (سنفترض قيم تجريبية هنا للعرض فقط)
            has_mfa = 1 if "MFA" in user_input.upper() or "FACTOR" in user_input.upper() else 0

            # استدعاء موديل XGBoost للتوقع
            prediction = predict_company_risk(has_mfa, 0, 0) # الدالة التي كتبناها سابقاً

            # 3. عرض النتائج بشكل تفاعلي
            st.success("تم الانتهاء من التحليل!")

            st.metric(label="الغرامة المتوقعة (بناءً على السوابق)", value=f"£{prediction:,.2f}")

            # عرض مستوى المخاطرة
            if prediction > 1000000:
                st.error("مستوى المخاطرة: عالٍ جداً (High Risk)")
            else:
                st.warning("مستوى المخاطرة: متوسط")

            st.info(f"التحليل القانوني: النظام وجد تشابهاً مع قضية LastPass بسبب ثغرة الـ MFA.")
    else:
        st.error("رجاءً ادخلي نصاً للتحليل")

!pip install shap

import shap

# 1. إنشاء مفسر للموديل الذي دربناه (XGBoost)
explainer = shap.TreeExplainer(model_xgb)

# 2. حساب قيم SHAP لبيانات التدريب
shap_values = explainer.shap_values(X)

# 3. رسم بياني يوضح تأثير كل ميزة على قيمة الغرامة
st.subheader("تحليل مسببات الغرامة (Explainability)")
shap.summary_plot(shap_values, X, plot_type="bar")

# دالة لشرح قرار معين لشركة محددة
def explain_prediction(sample_data):
    # حساب التفسير لحالة واحدة
    shap_val = explainer.shap_values(sample_data)

    # ترتيب الميزات حسب التأثير
    feature_names = X.columns
    impact = dict(zip(feature_names, shap_val[0]))

    print("--- 🧠 لماذا توقع النظام هذه القيمة؟ ---")
    for feature, value in impact.items():
        importance = "إيجابي (يرفع الغرامة)" if value > 0 else "سلبي (يخفض الغرامة)"
        print(f"🔹 ميزة [{feature}]: تأثيرها {importance} بمقدار {abs(value):,.0f}")

# تجربة التفسير على حالة افتراضية
sample = np.array([[1, 0, 0]]) # شركة عندها مشكلة MFA
explain_prediction(sample)

import streamlit as st
import pandas as pd
import numpy as np
import shap
import matplotlib.pyplot as plt

# --- 1. إعدادات الواجهة ---
st.set_page_config(page_title="UK GDPR Risk Analyzer", layout="wide")
st.title("🛡️ محاكي مخاطر الامتثال البريطاني (UK GDPR)")
st.write("اكتبي تفاصيل الحدث التقني وسيقوم النظام بتوقع الغرامة بناءً على سوابق الـ ICO.")

# --- 2. منطقة الإدخال ---
with st.sidebar:
    st.header("بيانات الشركة")
    company_name = st.text_input("اسم الشركة", "Example Ltd")
    industry = st.selectbox("القطاع", ["Financial Services", "Retail", "Technology", "Healthcare"])
    is_uk_based = st.checkbox("هل المقر في بريطانيا؟", value=True)

user_problem = st.text_area("وصف المشكلة القانونية / التقنية:",
                             height=200,
                             placeholder="مثال: حدث تسريب لبيانات العملاء بسبب عدم تفعيل MFA...")

# --- 3. محرك التحليل (الربط مع الموديلات) ---
if st.button("تحليل المخاطر فوراً"):
    if user_problem:
        # أ- استخراج الميزات برمجياً من النص (Feature Extraction)
        has_mfa = 1 if any(w in user_problem.upper() for w in ["MFA", "MULTI-FACTOR", "AUTHENTICATION"]) else 0
        has_children = 1 if "children" in user_problem.lower() else 0

        # ب- التوقع باستخدام XGBoost
        # سنستخدم الموديل model_xgb الذي دربناه سابقاً
        input_features = np.array([[has_mfa, has_children, 0]]) # 0 هو رقم الـ Cluster الافتراضي
        prediction = model_xgb.predict(input_features)[0]
        fine_amount = max(0, prediction)

        # ج- عرض النتائج (Metrics)
        col1, col2, col3 = st.columns(3)
        col1.metric("الغرامة المتوقعة", f"£{fine_amount:,.0f}")
        col2.metric("مستوى الخطورة", "عالي" if fine_amount > 1000000 else "متوسط")
        col3.metric("الحالة المشابهة", "LastPass / Capita" if has_mfa else "MediaLab")

        # د- التفسير باستخدام SHAP
        st.subheader("📊 تحليل أسباب القرار (Explainability)")
        explainer = shap.TreeExplainer(model_xgb)
        shap_values = explainer.shap_values(input_features)

        # رسم بياني للتفسير
        fig, ax = plt.subplots()
        shap.bar_plot(shap_values[0], feature_names=['MFA Failure', 'Children Privacy', 'Cluster'], show=False)
        st.pyplot(fig)

        # هـ- التوصيات القانونية
        st.subheader("💡 توصيات للشركة:")
        if has_mfa:
            st.error("❗ يجب تفعيل الـ MFA فوراً على جميع الحسابات الحساسة لتقليل الغرامة بنسبة تصل لـ 40%.")
        if has_children:
            st.error("❗ يجب إجراء DPIA فوراً لتقييم أثر البيانات على الأطفال.")
    else:
        st.warning("الرجاء إدخال وصف للمشكلة للبدء.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import shap
# import matplotlib.pyplot as plt
# import xgboost as xgb
# 
# # استدعاء الموديل (تأكدي أن الموديل model_xgb موجود في ذاكرة كولاب)
# # ملاحظة: في بيئة العمل الحقيقية يفضل حفظ الموديل باستخدام pickle وتحميله هنا
# 
# st.set_page_config(page_title="UK GDPR Risk Analyzer", layout="wide")
# 
# st.title("🛡️ محاكي مخاطر الامتثال البريطاني (UK GDPR)")
# st.markdown("---")
# 
# # منطقة الإدخال
# user_problem = st.text_area("صف المشكلة أو الثغرة التقنية هنا:",
#                              height=150,
#                              placeholder="مثال: اختراق لقاعدة البيانات بسبب غياب التحقق الثنائي MFA...")
# 
# if st.button("تحليل المخاطر"):
#     if user_problem:
#         # استخراج الميزات (Feature Extraction)
#         has_mfa = 1 if any(w in user_problem.upper() for w in ["MFA", "MULTI-FACTOR"]) else 0
#         has_children = 1 if "children" in user_problem.lower() else 0
# 
#         # التوقع (بناءً على الموديل المدرب)
#         # ملاحظة: سنستخدم قيم افتراضية إذا لم يتم تمرير الموديل الفعلي في هذه الخلية
#         input_features = np.array([[has_mfa, has_children, 0]])
# 
#         # توقع تجريبي (أو استخدمي الموديل الخاص بكِ إذا قمتِ بتعريفه في نفس الملف)
#         fine_amount = 3000000 if has_mfa else 150000
# 
#         st.metric("الغرامة المتوقعة", f"£{fine_amount:,.0f}")
# 
#         if has_mfa:
#             st.error("⚠️ تحليل قانوني: هذه الحالة تشبه سوابق ICO الصارمة تجاه غياب الـ MFA (مثل LastPass).")
#         else:
#             st.info("ℹ️ الحالة مستقرة نسبياً ولكنها تتطلب مراجعة دورية.")
#     else:
#         st.warning("برجاء إدخال النص أولاً.")

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import numpy as np

# 1. تجهيز المدخلات (X) والمخرج (y)
# الميزات: فشل MFA، خصوصية الأطفال، ورقم المجموعة التي استخرجها BERT
X = df_final[['mfa_failure', 'children_privacy', 'cluster_id']]
y = df_final['fine_amount']

# 2. تقسيم البيانات (للتدريب والاختبار)
# ملاحظة: لأن البيانات قليلة حالياً، سنستخدمها كلها للتدريب ليفهم الموديل الأنماط
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. بناء وتدريب موديل XGBoost
# استخدمنا Regressor لأننا نتوقع "رقم" (قيمة الغرامة) وليس مجرد تصنيف
model_predictor = xgb.XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    objective='reg:squarederror'
)

model_predictor.fit(X_train, y_train)

print("✅ تم تدريب موديل التوقع بنجاح!")

# 4. تجربة سريعة: لنفترض رفعنا ملف لشركة جديدة عندها فشل في الـ MFA
# وهي تنتمي للمجموعة رقم 0 (مجموعة العقوبات التقنية)
sample_company = np.array([[1, 0, 0]]) # MFA failure = 1, Children = 0, Cluster = 0
prediction = model_predictor.predict(sample_company)

print(f"🔮 التوقع القانوني: الغرامة المحتملة لهذه الحالة هي £{prediction[0]:,.2f}")

def legal_advisor_engine(new_file_path):
    print(f"🔍 جاري تحليل الملف: {new_file_path}")

    # 1. استخراج النص من الملف الجديد
    new_text = extract_text(new_file_path)

    # 2. فهم المعنى القانوني باستخدام BERT
    new_vector = get_legal_embedding(new_text).reshape(1, -1)

    # 3. تحديد المجموعة (Cluster) التي ينتمي لها الملف
    assigned_cluster = kmeans.predict(new_vector)[0]

    # 4. استخراج الميزات (Feature Extraction)
    has_mfa = 1 if "MFA" in new_text.upper() or "MULTI-FACTOR" in new_text.upper() else 0
    is_children = 1 if "children" in new_text.lower() or "minor" in new_text.lower() else 0

    # 5. التوقع المالي باستخدام XGBoost
    features = np.array([[has_mfa, is_children, assigned_cluster]])
    predicted_fine = model_predictor.predict(features)[0]

    # 6. كتابة التقرير الاستشاري
    print("-" * 30)
    print("📋 التقرير الاستشاري المبدئي (UK GDPR Focus):")
    print(f"📍 المجموعة القانونية المرتبطة: {assigned_cluster}")

    if has_mfa == 1:
        print("⚠️ تنبيه: تم اكتشاف إشارات لضعف في أنظمة التحقق (MFA).")

    if predicted_fine > 0:
        print(f"💰 الغرامة المتوقعة بناءً على سوابق ICO: £{max(0, predicted_fine):,.2f}")
    else:
        print("✅ النظام يرى مخاطر منخفضة بناءً على المعطيات الحالية.")

    print("-" * 30)

# --- تجربة النظام ---
# يمكنك الآن رفع ملف جديد تماماً وتجربته هنا
# مثلاً: legal_advisor_engine("new_company_policy.pdf")

!pip install gradio

import gradio as gr

def analyze_document_ui(file):
    # 1. الحصول على مسار الملف المرفوع
    file_path = file.name

    # 2. استخراج النص
    text = extract_text(file_path)

    # 3. المعالجة عبر الموديلات (BERT & XGBoost)
    vector = get_legal_embedding(text).reshape(1, -1)
    cluster = kmeans.predict(vector)[0]

    has_mfa = 1 if "MFA" in text.upper() or "MULTI-FACTOR" in text.upper() else 0
    is_children = 1 if "children" in text.lower() or "minor" in text.lower() else 0

    features = np.array([[has_mfa, is_children, cluster]])
    prediction = model_predictor.predict(features)[0]
    prediction = max(0, prediction) # التأكد أن الغرامة ليست بالسالب

    # 4. تنسيق النتيجة للعرض في الواجهة
    risk_level = "High" if prediction > 1000000 else "Medium" if prediction > 0 else "Low"

    result_html = f"""
    <div style='text-align: center; padding: 20px; border-radius: 10px; background-color: #f0f2f6;'>
        <h2 style='color: #2e4053;'>UK GDPR Risk Assessment</h2>
        <hr>
        <p style='font-size: 18px;'><b>Assigned Cluster:</b> {cluster}</p>
        <p style='font-size: 20px; color: {"#e74c3c" if risk_level=="High" else "#f39c12"};'>
            <b>Risk Level:</b> {risk_level}
        </p>
        <h1 style='color: #1a5276;'>Predicted Fine: £{prediction:,.2f}</h1>
        <p style='font-size: 14px; color: #7f8c8d;'>*Based on historical ICO penalty notices and similarity analysis.</p>
    </div>
    """
    return result_html

# بناء واجهة Gradio
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# ⚖️ AI Legal Consultant (UK Edition)")
    gr.Markdown("Upload a Privacy Policy or a Technical Report to predict potential UK GDPR fines.")

    with gr.Row():
        file_input = gr.File(label="Upload Legal Document (PDF or DOCX)")
        output_html = gr.HTML()

    analyze_btn = gr.Button("Run Risk Analysis", variant="primary")
    analyze_btn.click(fn=analyze_document_ui, inputs=file_input, outputs=output_html)

# تشغيل الواجهة
demo.launch(debug=True)

def get_legal_explanation(text, predicted_fine):
    explanations = []

    # ربط الكلمات التقنية بالمواد القانونية في UK GDPR
    checks = {
        "MFA": ("Article 32", "فشل في تأمين البيانات (Security of processing) - غياب التحقق الثنائي."),
        "children": ("Article 8", "مخالفة شروط معالجة بيانات الأطفال (Conditions applicable to child's consent)."),
        "transparency": ("Article 12", "نقص في الشفافية في عرض المعلومات للجمهور."),
        "retention": ("Article 5(1)(e)", "الاحتفاظ بالبيانات لفترة أطول من اللازم (Storage limitation)."),
        "cooperation": ("Article 31", "عدم التعاون الكافي مع مكتب مفوض المعلومات (ICO).")
    }

    for key, (article, desc) in checks.items():
        if key.lower() in text.lower():
            explanations.append(f"⚖️ <b>{article}:</b> {desc}")

    if not explanations:
        explanations.append("✅ لم يتم رصد مخالفات صريحة للمواد الأساسية الشائعة.")

    return "<br>".join(explanations)

# تحديث دالة الواجهة لتشمل التفسير
def analyze_document_with_explanation(file):
    file_path = file.name
    text = extract_text(file_path)

    # التحليلات السابقة
    vector = get_legal_embedding(text).reshape(1, -1)
    cluster = kmeans.predict(vector)[0]
    has_mfa = 1 if "mfa" in text.lower() else 0
    is_children = 1 if "children" in text.lower() else 0

    # التوقع
    features = np.array([[has_mfa, is_children, cluster]])
    prediction = max(0, model_predictor.predict(features)[0])

    # توليد التفسير القانوني
    legal_reasons = get_legal_explanation(text, prediction)

    result_html = f"""
    <div style='font-family: sans-serif; border: 2px solid #1a5276; border-radius: 15px; overflow: hidden;'>
        <div style='background-color: #1a5276; color: white; padding: 10px; text-align: center;'>
            <h3>Report Summary - UK GDPR Assessment</h3>
        </div>
        <div style='padding: 20px; background-color: white
